/**
 * Banque de questions.
 *
 * Le contenu vit dans un fichier plutôt qu'en SQL : on le relit, on le
 * corrige et on l'étend sans quitter l'éditeur, et les variantes acceptées
 * se listent naturellement.
 *
 * Trois règles de rédaction tenues partout :
 *   · toute réponse écrite porte ses variantes acceptées, sans quoi la
 *     machine ne peut rien noter et l'hôte arbitre tout ;
 *   · une estimation ne porte jamais sur un chiffre invérifiable, sinon la
 *     partie tourne à la dispute ;
 *   · une question « citez N » a toujours bien plus de réponses valables
 *     que le nombre demandé — sinon ce n'est plus une liste, c'est un piège.
 */

/** Réponse écrite : `accepted` liste toutes les formulations valables. */
const ecrite = (theme, prompt, accepted, points = 1, hint = null) => ({
  theme,
  kind: 'ecrite',
  prompt,
  points,
  hint,
  payload: {},
  answer: { accepted },
})

/** « Citez N » : `accepted` est le vivier, `count` ce qu'on demande. */
const liste = (theme, prompt, count, accepted, points = 2, hint = null) => ({
  theme,
  kind: 'liste',
  prompt,
  points,
  hint,
  payload: { count },
  answer: { accepted, count },
})

const estimation = (theme, prompt, value, unit, points = 2, hint = null) => ({
  theme,
  kind: 'estimation',
  prompt,
  points,
  hint,
  payload: { unit },
  answer: value,
})

/** Classement : `order` est la bonne réponse ; les items sont mélangés au jeu. */
const classement = (theme, prompt, order, topLabel, bottomLabel, points = 2) => ({
  theme,
  kind: 'classement',
  prompt,
  points,
  hint: null,
  payload: { items: [...order].reverse(), topLabel, bottomLabel },
  answer: order,
})

const intrus = (theme, prompt, items, odd, points = 1, hint = null) => ({
  theme,
  kind: 'intrus',
  prompt,
  points,
  hint,
  payload: { items },
  answer: odd,
})

export const QUESTIONS = [
  // ═══ Géographie ═══════════════════════════════════════════════════════
  liste('Géographie', 'Citez 4 pays d’Océanie', 4, [
    'Australie', 'Nouvelle-Zélande', 'Papouasie-Nouvelle-Guinée', 'Fidji',
    'Samoa', 'Tonga', 'Vanuatu', 'Palaos', 'Nauru', 'Tuvalu', 'Kiribati',
    'Micronésie', 'Îles Marshall', 'Îles Salomon',
  ]),
  liste('Géographie', 'Citez 3 pays traversés par le Danube', 3, [
    'Allemagne', 'Autriche', 'Slovaquie', 'Hongrie', 'Croatie', 'Serbie',
    'Roumanie', 'Bulgarie', 'Moldavie', 'Ukraine',
  ]),
  liste('Géographie', 'Citez 4 pays d’Amérique du Sud', 4, [
    'Brésil', 'Argentine', 'Chili', 'Pérou', 'Colombie', 'Bolivie', 'Équateur',
    'Venezuela', 'Paraguay', 'Uruguay', 'Guyana', 'Suriname',
  ]),
  liste('Géographie', 'Citez 3 pays européens sans accès à la mer', 3, [
    'Suisse', 'Autriche', 'Hongrie', 'Slovaquie', 'Tchéquie', 'Serbie',
    'Luxembourg', 'Biélorussie', 'Moldavie', 'Macédoine du Nord', 'Kosovo',
    'Andorre', 'Liechtenstein', 'Saint-Marin', 'Vatican',
  ]),
  liste('Géographie', 'Citez 4 fleuves français', 4, [
    'Loire', 'Seine', 'Rhône', 'Garonne', 'Rhin', 'Meuse', 'Adour', 'Charente',
    'Somme', 'Orne', 'Vilaine', 'Var', 'Aude', 'Hérault',
  ]),
  liste('Géographie', 'Citez 3 pays frontaliers de l’Allemagne', 3, [
    'France', 'Belgique', 'Pays-Bas', 'Luxembourg', 'Danemark', 'Pologne',
    'Tchéquie', 'Autriche', 'Suisse',
  ]),
  liste('Géographie', 'Citez 4 capitales africaines', 4, [
    'Le Caire', 'Rabat', 'Alger', 'Tunis', 'Dakar', 'Accra', 'Abuja', 'Nairobi',
    'Addis-Abeba', 'Pretoria', 'Bamako', 'Ouagadougou', 'Yaoundé', 'Kinshasa',
    'Antananarivo', 'Tripoli', 'Khartoum', 'Lusaka', 'Harare', 'Kampala',
  ]),
  ecrite('Géographie', 'Quelle est la capitale de l’Australie ?', ['Canberra'], 1,
    'Ce n’est ni Sydney ni Melbourne'),
  ecrite('Géographie', 'Quel détroit sépare l’Europe de l’Afrique ?',
    ['Détroit de Gibraltar', 'Gibraltar']),
  ecrite('Géographie', 'Quel est le plus grand désert chaud du monde ?', ['Sahara']),
  ecrite('Géographie', 'Dans quel pays se trouve le Machu Picchu ?', ['Pérou']),
  ecrite('Géographie', 'Quelle est la mer la plus salée du monde ?', ['Mer Morte'], 2),
  ecrite('Géographie', 'Quel pays compte le plus de fuseaux horaires ?', ['France'], 3,
    'Grâce à ses territoires d’outre-mer'),
  ecrite('Géographie', 'Quelle chaîne de montagnes sépare l’Europe de l’Asie ?',
    ['Oural', 'Monts Oural'], 2),
  ecrite('Géographie', 'Quelle est la plus grande île du monde ?', ['Groenland']),
  estimation('Géographie', 'Combien de communes compte la France ?', 34945, 'communes'),
  estimation('Géographie', 'Quelle est l’altitude du mont Blanc ?', 4806, 'mètres'),
  estimation('Géographie', 'Combien de pays sont membres de l’ONU ?', 193, 'pays'),
  estimation('Géographie', 'Quelle est la superficie de la France métropolitaine ?',
    551695, 'km²'),
  estimation('Géographie', 'Combien d’habitants compte l’agglomération de Tokyo ?',
    37000000, 'habitants'),
  estimation('Géographie', 'Quelle est la profondeur de la fosse des Mariannes ?',
    10994, 'mètres'),
  classement('Géographie', 'Classez ces pays du plus peuplé au moins peuplé',
    ['Inde', 'Chine', 'États-Unis', 'Indonésie', 'Brésil'],
    'Le plus peuplé', 'Le moins peuplé'),
  classement('Géographie', 'Classez ces fleuves du plus long au plus court',
    ['Nil', 'Amazone', 'Yangtsé', 'Mississippi', 'Danube'],
    'Le plus long', 'Le plus court'),
  classement('Géographie', 'Classez ces villes de la plus au nord à la plus au sud',
    ['Oslo', 'Berlin', 'Paris', 'Madrid', 'Alger'],
    'La plus au nord', 'La plus au sud'),
  classement('Géographie', 'Classez ces pays du plus grand au plus petit',
    ['Russie', 'Canada', 'Chine', 'Brésil', 'Australie'],
    'Le plus grand', 'Le plus petit'),
  intrus('Géographie', 'Lequel n’est pas une île ?',
    ['Madagascar', 'Sri Lanka', 'Mongolie', 'Islande', 'Cuba'], 'Mongolie'),
  intrus('Géographie', 'Laquelle n’est pas une capitale ?',
    ['Lima', 'Quito', 'Rio de Janeiro', 'Bogota', 'Santiago'], 'Rio de Janeiro'),
  intrus('Géographie', 'Lequel n’est pas un pays d’Asie ?',
    ['Népal', 'Bhoutan', 'Botswana', 'Laos', 'Cambodge'], 'Botswana'),

  // ═══ Histoire ═════════════════════════════════════════════════════════
  ecrite('Histoire', 'En quelle année la Révolution française a-t-elle commencé ?',
    ['1789']),
  ecrite('Histoire', 'Qui fut le premier président de la Ve République ?',
    ['Charles de Gaulle', 'De Gaulle', 'Gaulle']),
  ecrite('Histoire', 'Quel mur est tombé en 1989 ?', ['Mur de Berlin', 'Berlin']),
  ecrite('Histoire', 'Qui fut la première femme à recevoir un prix Nobel ?',
    ['Marie Curie', 'Curie'], 2),
  ecrite('Histoire', 'Quelle civilisation a construit Chichén Itzá ?',
    ['Mayas', 'Maya'], 2),
  ecrite('Histoire', 'En quelle année l’homme a-t-il marché sur la Lune ?', ['1969']),
  ecrite('Histoire', 'Quel empereur romain a fait bâtir un mur en Angleterre ?',
    ['Hadrien'], 2),
  ecrite('Histoire', 'Quel pharaon a fait construire la plus grande pyramide de Gizeh ?',
    ['Khéops', 'Chéops'], 2),
  ecrite('Histoire', 'Quelle bataille Napoléon a-t-il perdue en 1815 ?', ['Waterloo']),
  ecrite('Histoire', 'Qui a peint le plafond de la chapelle Sixtine ?',
    ['Michel-Ange', 'Michelangelo'], 2),
  liste('Histoire', 'Citez 3 rois de France prénommés Louis', 3, [
    'Louis XIV', 'Louis XVI', 'Louis XV', 'Louis XIII', 'Louis IX', 'Saint Louis',
    'Louis XI', 'Louis XVIII', 'Louis-Philippe', 'Louis VIII', 'Louis X',
  ]),
  liste('Histoire', 'Citez 3 pays fondateurs de la Communauté européenne', 3, [
    'France', 'Allemagne', 'Italie', 'Belgique', 'Pays-Bas', 'Luxembourg',
  ]),
  liste('Histoire', 'Citez 3 présidents de la République française', 3, [
    'Charles de Gaulle', 'Georges Pompidou', 'Valéry Giscard d’Estaing',
    'François Mitterrand', 'Jacques Chirac', 'Nicolas Sarkozy',
    'François Hollande', 'Emmanuel Macron', 'Vincent Auriol', 'René Coty',
  ]),
  liste('Histoire', 'Citez 3 des sept merveilles du monde antique', 3, [
    'Pyramide de Khéops', 'Jardins suspendus de Babylone', 'Temple d’Artémis',
    'Statue de Zeus', 'Mausolée d’Halicarnasse', 'Colosse de Rhodes',
    'Phare d’Alexandrie',
  ], 3),
  estimation('Histoire', 'En quelle année fut signé le traité de Versailles ?', 1919, '', 1),
  estimation('Histoire', 'Combien de temps a duré la guerre de Cent Ans ?', 116, 'ans'),
  estimation('Histoire', 'En quelle année la tour Eiffel a-t-elle été inaugurée ?',
    1889, '', 1),
  estimation('Histoire', 'Combien de temps a duré le règne de Louis XIV ?', 72, 'ans'),
  classement('Histoire', 'Classez ces événements du plus ancien au plus récent',
    ['Chute de l’Empire romain', 'Découverte de l’Amérique', 'Révolution française',
      'Première Guerre mondiale', 'Chute du mur de Berlin'],
    'Le plus ancien', 'Le plus récent'),
  classement('Histoire', 'Classez ces inventions par ordre d’apparition',
    ['Imprimerie', 'Machine à vapeur', 'Téléphone', 'Télévision', 'Internet'],
    'La plus ancienne', 'La plus récente'),
  classement('Histoire', 'Classez ces civilisations de la plus ancienne à la plus récente',
    ['Sumériens', 'Égyptiens', 'Grecs', 'Romains', 'Aztèques'],
    'La plus ancienne', 'La plus récente'),

  // ═══ Sciences ═════════════════════════════════════════════════════════
  ecrite('Sciences', 'Quel est le symbole chimique de l’or ?', ['Au']),
  ecrite('Sciences', 'Quelle planète est la plus proche du Soleil ?', ['Mercure']),
  ecrite('Sciences', 'Combien d’os compte le corps humain adulte ?', ['206'], 2),
  ecrite('Sciences', 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?',
    ['Dioxyde de carbone', 'CO2', 'Gaz carbonique']),
  ecrite('Sciences', 'Qui a formulé la théorie de la relativité ?',
    ['Albert Einstein', 'Einstein']),
  ecrite('Sciences', 'Quel est l’organe le plus grand du corps humain ?', ['Peau']),
  ecrite('Sciences', 'Quelle est l’unité de mesure de la force ?', ['Newton'], 2),
  ecrite('Sciences', 'Quel est l’élément le plus abondant dans l’univers ?',
    ['Hydrogène'], 2),
  ecrite('Sciences', 'Quelle particule porte une charge négative ?', ['Électron']),
  ecrite('Sciences', 'Qui a énoncé la loi de la gravitation universelle ?',
    ['Isaac Newton', 'Newton']),
  liste('Sciences', 'Citez 4 planètes du système solaire', 4, [
    'Mercure', 'Vénus', 'Terre', 'Mars', 'Jupiter', 'Saturne', 'Uranus', 'Neptune',
  ]),
  liste('Sciences', 'Citez 3 gaz nobles', 3,
    ['Hélium', 'Néon', 'Argon', 'Krypton', 'Xénon', 'Radon'], 2,
    'Ils occupent la dernière colonne du tableau périodique'),
  liste('Sciences', 'Citez 3 os du corps humain', 3, [
    'Fémur', 'Tibia', 'Péroné', 'Humérus', 'Radius', 'Cubitus', 'Ulna',
    'Clavicule', 'Sternum', 'Crâne', 'Mandibule', 'Rotule', 'Omoplate',
    'Scapula', 'Vertèbre', 'Côte', 'Bassin', 'Phalange',
  ]),
  liste('Sciences', 'Citez 3 sens humains', 3,
    ['Vue', 'Ouïe', 'Odorat', 'Goût', 'Toucher'], 1),
  estimation('Sciences', 'À quelle vitesse voyage la lumière, en kilomètres par seconde ?',
    299792, 'km/s'),
  estimation('Sciences', 'Combien de temps met la lumière du Soleil à nous parvenir ?',
    8, 'minutes'),
  estimation('Sciences', 'Combien de chromosomes compte une cellule humaine ?',
    46, 'chromosomes'),
  estimation('Sciences', 'Quelle est la température de surface du Soleil ?',
    5500, 'degrés'),
  estimation('Sciences', 'Combien de litres de sang circulent dans un corps adulte ?',
    5, 'litres'),
  classement('Sciences',
    'Classez ces planètes de la plus proche du Soleil à la plus lointaine',
    ['Mercure', 'Vénus', 'Terre', 'Mars', 'Jupiter'],
    'La plus proche', 'La plus lointaine'),
  classement('Sciences', 'Classez ces animaux du plus rapide au plus lent',
    ['Guépard', 'Cheval', 'Lion', 'Éléphant', 'Tortue'],
    'Le plus rapide', 'Le plus lent'),
  classement('Sciences', 'Classez ces éléments du plus léger au plus lourd',
    ['Hydrogène', 'Hélium', 'Carbone', 'Fer', 'Or'],
    'Le plus léger', 'Le plus lourd'),
  intrus('Sciences', 'Lequel n’est pas un métal ?',
    ['Fer', 'Cuivre', 'Soufre', 'Zinc', 'Nickel'], 'Soufre'),
  intrus('Sciences', 'Lequel n’est pas un mammifère ?',
    ['Dauphin', 'Chauve-souris', 'Requin', 'Baleine', 'Ornithorynque'], 'Requin'),
  intrus('Sciences', 'Laquelle n’est plus considérée comme une planète ?',
    ['Vénus', 'Neptune', 'Pluton', 'Uranus', 'Saturne'], 'Pluton'),

  // ═══ Cinéma ═══════════════════════════════════════════════════════════
  ecrite('Cinéma', 'Qui a réalisé « Pulp Fiction » ?',
    ['Quentin Tarantino', 'Tarantino']),
  ecrite('Cinéma', 'Quel film a remporté l’Oscar du meilleur film en 2020 ?',
    ['Parasite']),
  ecrite('Cinéma', 'Comment s’appelle le vaisseau de Han Solo ?',
    ['Faucon Millenium', 'Millennium Falcon'], 2),
  ecrite('Cinéma', 'Quel studio d’animation a créé « Mon voisin Totoro » ?',
    ['Studio Ghibli', 'Ghibli']),
  ecrite('Cinéma', 'Qui joue Jack dans « Titanic » ?',
    ['Leonardo DiCaprio', 'DiCaprio']),
  ecrite('Cinéma', 'Quel réalisateur a signé « Inception » et « Interstellar » ?',
    ['Christopher Nolan', 'Nolan']),
  liste('Cinéma', 'Citez 3 films de la saga Star Wars', 3, [
    'Un nouvel espoir', 'L’Empire contre-attaque', 'Le Retour du Jedi',
    'La Menace fantôme', 'L’Attaque des clones', 'La Revanche des Sith',
    'Le Réveil de la Force', 'Les Derniers Jedi', 'L’Ascension de Skywalker',
    'Rogue One', 'Solo',
  ]),
  liste('Cinéma', 'Citez 3 films d’animation Pixar', 3, [
    'Toy Story', 'Le Monde de Nemo', 'Les Indestructibles', 'Ratatouille',
    'Wall-E', 'Là-haut', 'Vice-versa', 'Coco', 'Cars', 'Monstres et Cie',
    'Rebelle', 'Soul', 'Luca', 'Le Voyage d’Arlo',
  ]),
  liste('Cinéma', 'Citez 3 super-héros Marvel', 3, [
    'Iron Man', 'Captain America', 'Thor', 'Hulk', 'Spider-Man', 'Black Widow',
    'Docteur Strange', 'Black Panther', 'Ant-Man', 'Wolverine', 'Deadpool',
    'Daredevil', 'Captain Marvel', 'Hawkeye', 'Faucon',
  ], 1),
  estimation('Cinéma', 'En quelle année est sorti le premier film Star Wars ?',
    1977, '', 1),
  estimation('Cinéma', 'Combien de films compte la saga Harry Potter ?', 8, 'films', 1),
  classement('Cinéma', 'Classez ces films du plus ancien au plus récent',
    ['Le Parrain', 'Star Wars', 'Retour vers le futur', 'Titanic', 'Avatar'],
    'Le plus ancien', 'Le plus récent'),
  intrus('Cinéma', 'Lequel n’est pas un film de Christopher Nolan ?',
    ['Inception', 'Interstellar', 'Gravity', 'Dunkerque', 'Tenet'], 'Gravity'),

  // ═══ Musique ══════════════════════════════════════════════════════════
  ecrite('Musique', 'Combien de touches compte un piano standard ?', ['88']),
  ecrite('Musique', 'Quel groupe a chanté « Bohemian Rhapsody » ?', ['Queen']),
  ecrite('Musique', 'Quel compositeur est devenu sourd ?',
    ['Beethoven', 'Ludwig van Beethoven']),
  ecrite('Musique', 'De quelle ville viennent les Beatles ?', ['Liverpool']),
  ecrite('Musique', 'De quel instrument Miles Davis jouait-il ?', ['Trompette'], 2),
  liste('Musique', 'Citez 3 instruments à cordes', 3, [
    'Violon', 'Alto', 'Violoncelle', 'Contrebasse', 'Guitare', 'Harpe', 'Banjo',
    'Mandoline', 'Ukulélé', 'Luth', 'Sitar', 'Piano',
  ], 1),
  liste('Musique', 'Citez 4 notes de la gamme', 4,
    ['Do', 'Ré', 'Mi', 'Fa', 'Sol', 'La', 'Si'], 1),
  liste('Musique', 'Citez 3 membres des Beatles', 3, [
    'John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr',
    'Lennon', 'McCartney', 'Harrison', 'Starr',
  ]),
  classement('Musique', 'Classez ces genres par ordre d’apparition',
    ['Jazz', 'Rock', 'Disco', 'Hip-hop', 'Techno'],
    'Le plus ancien', 'Le plus récent'),
  intrus('Musique', 'Lequel n’est pas un instrument à vent ?',
    ['Flûte', 'Trompette', 'Violoncelle', 'Clarinette', 'Saxophone'], 'Violoncelle'),

  // ═══ Littérature ══════════════════════════════════════════════════════
  ecrite('Littérature', 'Qui a écrit « Les Misérables » ?', ['Victor Hugo', 'Hugo']),
  ecrite('Littérature', 'Qui a écrit « Le Petit Prince » ?',
    ['Antoine de Saint-Exupéry', 'Saint-Exupéry']),
  ecrite('Littérature', 'Quel écrivain a créé Sherlock Holmes ?',
    ['Arthur Conan Doyle', 'Conan Doyle']),
  ecrite('Littérature', 'Dans quel roman trouve-t-on le capitaine Achab ?',
    ['Moby Dick']),
  ecrite('Littérature', 'Qui a écrit « 1984 » ?', ['George Orwell', 'Orwell']),
  liste('Littérature', 'Citez 3 romans de Jules Verne', 3, [
    'Vingt mille lieues sous les mers', 'Le Tour du monde en quatre-vingts jours',
    'Voyage au centre de la Terre', 'De la Terre à la Lune', 'L’Île mystérieuse',
    'Michel Strogoff', 'Cinq semaines en ballon',
  ], 3),
  liste('Littérature', 'Citez 3 maisons de Poudlard', 3,
    ['Gryffondor', 'Serpentard', 'Serdaigle', 'Poufsouffle'], 1),
  intrus('Littérature', 'Lequel n’a pas écrit de roman policier ?',
    ['Agatha Christie', 'Georges Simenon', 'Marcel Proust', 'Conan Doyle',
      'Maurice Leblanc'], 'Marcel Proust'),

  // ═══ Sport ════════════════════════════════════════════════════════════
  ecrite('Sport', 'Combien de joueurs compte une équipe de football sur le terrain ?',
    ['11', 'Onze']),
  ecrite('Sport', 'Tous les combien d’années ont lieu les Jeux olympiques d’été ?',
    ['4', 'Quatre']),
  ecrite('Sport', 'Quel pays a remporté la Coupe du monde de football en 2018 ?',
    ['France']),
  ecrite('Sport', 'Sur quelle surface se joue Roland-Garros ?', ['Terre battue']),
  ecrite('Sport', 'Combien de joueurs compte une équipe de basket sur le terrain ?',
    ['5', 'Cinq']),
  liste('Sport', 'Citez 3 sports olympiques d’hiver', 3, [
    'Ski alpin', 'Ski de fond', 'Biathlon', 'Patinage artistique',
    'Patinage de vitesse', 'Hockey sur glace', 'Curling', 'Bobsleigh', 'Luge',
    'Skeleton', 'Snowboard', 'Saut à ski', 'Combiné nordique',
  ]),
  liste('Sport', 'Citez 3 tournois du Grand Chelem de tennis', 3,
    ['Roland-Garros', 'Wimbledon', 'US Open', 'Open d’Australie'], 1),
  estimation('Sport', 'Quelle est la longueur d’un marathon, en kilomètres ?',
    42, 'km', 1),
  estimation('Sport', 'Combien de trous compte un parcours de golf standard ?',
    18, 'trous', 1),
  classement('Sport',
    'Classez ces sports du plus ancien au plus récent aux Jeux olympiques',
    ['Athlétisme', 'Natation', 'Basketball', 'Volleyball', 'Skateboard'],
    'Le plus ancien', 'Le plus récent'),
  intrus('Sport', 'Lequel n’est pas un sport olympique ?',
    ['Escrime', 'Tir à l’arc', 'Cricket', 'Judo', 'Aviron'], 'Cricket'),

  // ═══ Gastronomie ══════════════════════════════════════════════════════
  ecrite('Gastronomie', 'De quel pays le sushi est-il originaire ?', ['Japon']),
  ecrite('Gastronomie', 'Quel ingrédient donne sa couleur au risotto milanais ?',
    ['Safran'], 2),
  ecrite('Gastronomie', 'Quel fromage entre dans la pizza margherita ?',
    ['Mozzarella']),
  ecrite('Gastronomie', 'Quelle céréale sert à faire le saké ?', ['Riz'], 2),
  liste('Gastronomie', 'Citez 3 fromages français', 3, [
    'Camembert', 'Roquefort', 'Comté', 'Brie', 'Reblochon', 'Munster', 'Cantal',
    'Beaufort', 'Bleu d’Auvergne', 'Époisses', 'Saint-Nectaire', 'Tomme',
    'Morbier', 'Maroilles', 'Chèvre',
  ], 1),
  liste('Gastronomie', 'Citez 3 épices', 3, [
    'Poivre', 'Cannelle', 'Curcuma', 'Cumin', 'Paprika', 'Safran', 'Gingembre',
    'Muscade', 'Clou de girofle', 'Coriandre', 'Cardamome', 'Piment', 'Curry',
    'Anis', 'Vanille',
  ], 1),
  liste('Gastronomie', 'Citez 3 régions viticoles françaises', 3, [
    'Bordeaux', 'Bourgogne', 'Champagne', 'Alsace', 'Loire', 'Rhône', 'Provence',
    'Languedoc', 'Beaujolais', 'Jura', 'Savoie', 'Corse',
  ]),
  intrus('Gastronomie', 'Lequel n’est pas un plat italien ?',
    ['Risotto', 'Osso buco', 'Paella', 'Carbonara', 'Tiramisu'], 'Paella'),

  // ═══ Nature ═══════════════════════════════════════════════════════════
  ecrite('Nature', 'Quel est le plus grand animal du monde ?',
    ['Baleine bleue', 'Rorqual bleu']),
  ecrite('Nature', 'Combien de pattes a une araignée ?', ['8', 'Huit']),
  ecrite('Nature', 'Quel est l’arbre le plus haut du monde ?', ['Séquoia'], 2),
  ecrite('Nature', 'Quel oiseau est le plus rapide en piqué ?',
    ['Faucon pèlerin', 'Faucon'], 2),
  ecrite('Nature', 'Combien de cœurs possède une pieuvre ?', ['3', 'Trois'], 3),
  liste('Nature', 'Citez 3 animaux qui hibernent', 3, [
    'Ours', 'Marmotte', 'Hérisson', 'Chauve-souris', 'Loir', 'Écureuil',
    'Grenouille', 'Tortue', 'Serpent', 'Escargot',
  ]),
  liste('Nature', 'Citez 4 félins', 4, [
    'Lion', 'Tigre', 'Léopard', 'Guépard', 'Jaguar', 'Panthère', 'Lynx', 'Puma',
    'Ocelot', 'Chat', 'Caracal', 'Serval',
  ], 1),
  liste('Nature', 'Citez 3 arbres à feuilles caduques', 3, [
    'Chêne', 'Hêtre', 'Bouleau', 'Érable', 'Frêne', 'Peuplier', 'Saule',
    'Tilleul', 'Châtaignier', 'Noyer', 'Orme', 'Charme', 'Platane',
  ]),
  estimation('Nature', 'Combien de temps vit une tortue géante des Galápagos ?',
    100, 'ans'),
  estimation('Nature', 'Combien d’espèces d’oiseaux existe-t-il dans le monde ?',
    10000, 'espèces'),
  classement('Nature', 'Classez ces animaux du plus lourd au plus léger',
    ['Baleine bleue', 'Éléphant', 'Girafe', 'Ours brun', 'Loup'],
    'Le plus lourd', 'Le plus léger'),
  intrus('Nature', 'Lequel n’est pas un insecte ?',
    ['Fourmi', 'Abeille', 'Araignée', 'Coccinelle', 'Libellule'], 'Araignée'),

  // ═══ Langue française ═════════════════════════════════════════════════
  ecrite('Langue française', 'Combien de lettres compte l’alphabet français ?',
    ['26', 'Vingt-six']),
  ecrite('Langue française', 'Quel est le pluriel de « cheval » ?', ['Chevaux']),
  ecrite('Langue française',
    'Comment appelle-t-on un mot qui se lit dans les deux sens ?',
    ['Palindrome'], 2),
  ecrite('Langue française', 'Quel est le contraire de « éphémère » ?',
    ['Durable', 'Éternel', 'Permanent', 'Pérenne'], 2),
  liste('Langue française', 'Citez 3 figures de style', 3, [
    'Métaphore', 'Comparaison', 'Hyperbole', 'Litote', 'Métonymie', 'Oxymore',
    'Anaphore', 'Allitération', 'Personnification', 'Euphémisme', 'Antithèse',
    'Ironie', 'Périphrase', 'Pléonasme',
  ]),
  liste('Langue française', 'Citez 3 temps de l’indicatif', 3, [
    'Présent', 'Imparfait', 'Passé simple', 'Passé composé', 'Futur simple',
    'Plus-que-parfait', 'Passé antérieur', 'Futur antérieur',
  ]),
  intrus('Langue française', 'Lequel n’est pas un synonyme de « rapide » ?',
    ['Véloce', 'Prompt', 'Placide', 'Vif', 'Preste'], 'Placide'),

  // ═══ Technologie ══════════════════════════════════════════════════════
  ecrite('Technologie', 'Que signifie « www » ?', ['World Wide Web']),
  ecrite('Technologie', 'Qui a fondé Microsoft avec Paul Allen ?',
    ['Bill Gates', 'Gates']),
  ecrite('Technologie', 'Combien de bits compte un octet ?', ['8', 'Huit']),
  ecrite('Technologie', 'Quel langage de programmation porte le nom d’un serpent ?',
    ['Python']),
  liste('Technologie', 'Citez 3 langages de programmation', 3, [
    'Python', 'JavaScript', 'Java', 'C', 'C++', 'C#', 'Ruby', 'Go', 'Rust',
    'PHP', 'Swift', 'Kotlin', 'TypeScript', 'SQL', 'Perl', 'Scala',
  ], 1),
  estimation('Technologie', 'En quelle année est sorti le premier iPhone ?',
    2007, '', 1),
  estimation('Technologie', 'Combien de méga-octets dans un giga-octet ?',
    1024, 'Mo', 1),
  classement('Technologie', 'Classez ces inventions par ordre d’apparition',
    ['Ordinateur personnel', 'Internet', 'Téléphone portable', 'Smartphone',
      'Réseaux sociaux'],
    'La plus ancienne', 'La plus récente'),

  // ═══ Arts ═════════════════════════════════════════════════════════════
  ecrite('Arts', 'Qui a peint « La Joconde » ?',
    ['Léonard de Vinci', 'De Vinci', 'Vinci']),
  ecrite('Arts', 'Dans quel musée se trouve « La Joconde » ?',
    ['Louvre', 'Musée du Louvre']),
  ecrite('Arts', 'Qui a peint « La Nuit étoilée » ?',
    ['Vincent van Gogh', 'Van Gogh']),
  ecrite('Arts', 'Quel mouvement artistique Salvador Dalí représente-t-il ?',
    ['Surréalisme'], 2),
  ecrite('Arts', 'Qui a sculpté « Le Penseur » ?', ['Auguste Rodin', 'Rodin']),
  liste('Arts', 'Citez 3 peintres impressionnistes', 3, [
    'Claude Monet', 'Monet', 'Renoir', 'Auguste Renoir', 'Degas', 'Edgar Degas',
    'Pissarro', 'Sisley', 'Manet', 'Berthe Morisot', 'Caillebotte',
  ], 3),
  liste('Arts', 'Citez 3 couleurs primaires ou secondaires', 3,
    ['Rouge', 'Bleu', 'Jaune', 'Vert', 'Orange', 'Violet'], 1),
  intrus('Arts', 'Lequel n’est pas un peintre ?',
    ['Picasso', 'Matisse', 'Rodin', 'Kandinsky', 'Klimt'], 'Rodin'),
]
